### ISSUE TITLE
Repo name should be guide-cloud-openshift-operator

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-cloud-openshift-operator#27]
Consider the repo name of "guide-cloud-openshift-operator" when this guide goes live.

This is consistent with the naming for the current published OpenShift guide and better reflects this guide under development as the guide for deploying to OpenShift using Open Liberty Operator.

**Comment by yeekangc** [comment]
In general, for the title, abstract, front matter as well as introduction, the focus should be on deploying to OpenShift first with using Operator as the secondary focus as the means to an end.

@MaiHameed @gkwan-ibm Cc @lauracowen

**Comment by MaiHameed** [comment]
Noted, thanks @yeekangc

**Comment by gkwan-ibm** [comment]
@MaiHameed update to
- Title: Deploying microservices to OpenShift using Kubernetes Operator
-  Short desc: Explore how to deploy microservices to Red Hat OpenShift by using the Open Liberty Operator.
- as well the first statement in the "What you’ll learn" section

cc @yeekangc anything else?

**Comment by yeekangc** [comment]
LGTM.  We can review the SEO metadata when ready.

**Comment by gkwan-ibm** [comment]
close
- repo name was renamed to guide-cloud-openshift-operator
- SEO was reviewed
